<?php

/**
 * @file
 * The main Islandora RSS Plus module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_rss_plus_menu() {
  return array(
    'admin/islandora/tools/rss-plus' => array(
      'title' => 'Islandora RSS Plus',
      'description' => 'Configure Solr fields for RSS Plus',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_rss_plus_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_solr_config_rss_item_post_render__alter().
 */
function islandora_rss_plus_islandora_solr_config_rss_item_post_render_alter(&$rendered_item, &$doc) {
  $item = new DOMDocument();
  $item->preserveWhiteSpace = FALSE;
  $item->formatOutput = TRUE;
  $item->loadXML($rendered_item);
  $pid = $doc['PID'];
  $rights_field = variable_get('islandora_rss_plus_field_rights', 'dc.rights');
  $subject_field = variable_get('islandora_rss_plus_field_subject', 'dc.subject');
  $publisher_field = variable_get('islandora_rss_plus_field_publisher', 'dc.publisher');
  $language_field = variable_get('islandora_rss_plus_field_language', 'dc.language');
  $results = islandora_rss_plus_get_fields($pid, $rights_field, $language_field, $subject_field, $publisher_field);
  $fragment = array();
  foreach($results AS $result) {
    if (!empty($result['solr_doc'][$rights_field])) {
      $rights = $result['solr_doc'][$rights_field];
    }
    if (!empty($result['solr_doc'][$language_field])) {
      $languages = $result['solr_doc'][$language_field];
    }
    if (!empty($result['solr_doc'][$publisher_field])) {
      $publishers = $result['solr_doc'][$publisher_field];
    }
    if (!empty($result['solr_doc'][$subject_field])) {
      $subjects = $result['solr_doc'][$subject_field];
    }
    if (!empty($rights)) {
      foreach ($rights AS $right) {
        $fragment[] = "<rights>" . $right . "</rights>";
      }
    }
    if (!empty($subjects)) {
      foreach ($subjects AS $subject) {
        $fragment[] = "<subject>" . $subject . "</subject>";
      }
    }
    if (!empty($publishers)) {
      foreach ($publishers AS $publisher) {
        $fragment[] = "<publisher>" . $publisher . "</publisher>";
      }
    }
    if (!empty($languages)) {
      foreach ($languages AS $language) {
        $fragment[] = "<language>" . $language . "</language>";
      }
    }
  }
    $full_fragment = '';
    foreach ($fragment AS $part) {
      $full_fragment = $full_fragment . $part;
    }
  if (!empty($full_fragment)) {
    $full_fragment=preg_replace('/&(?!#?[a-z0-9]+;)/', '&amp;', $full_fragment);
    $frag = $item->createDocumentFragment();
    $frag->appendXML($full_fragment);
    $item->documentElement->appendChild($frag);
    // Goal: Grab the appropriate Solr fields from the object and inject them into the rendered_item
  
    // Would do some manipulation of the DOM before this...
    $rendered_item = $item->saveXML($item->documentElement);
  }

}


function islandora_rss_plus_get_fields($pid, $rights_field, $language_field, $subject_field, $publisher_field) {
  // Gets the rightsstatements.org URI from the configured Solr field.
  $results = array();
  $qp = new islandoraSolrQueryProcessor();
  $qp->buildQuery(format_string('@field:"@pid"', array(
    '@field' => 'PID',
    '@pid' =>"{$pid}")
  ));
  $qp->solrParams['fl'] = implode(', ', array(
    'PID',
    $rights_field,
    $namespace_field,
    $subject_field,
    $publisher_field,
    $language_field,
  ));
  $qp->solrStart = 0;
  $qp->solrLimit = 100000;
  $qp->executeQuery(FALSE);


  $response = $qp->islandoraSolrResult['response']['objects'];
  return $response;
}

